config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#new'

  resources :user_sessions
  resources :users
  resources :medications
  resources :doctors
  resources :appointments

get 'history' => 'appointments#history', :as => :history
get 'profile' => 'users#show', :as => :profile

get 'register' => 'users#new', :as => :register
get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :user

  validates :doctor_id, :date, :time, presence: true

  scope :most_recent, -> {Appointment.where('date < ?', Date.today).order(date: :desc).limit(1)}
  scope :next_appt, -> {Appointment.where('date > ?', Date.today).order(date: :asc).limit(1)}
  
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :user
  has_many :appointments
  
  validates :name, :phone, :address, presence: true
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :user
  
  validates :name, :amount, :started_at, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :first_name, :email, :password, :password_confirmation, presence: true

  validates :email, uniqueness: true

  has_many :medications
  has_many :doctors
  has_many :appointments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  private 
  def not_authenticated
    redirect_to login_path, alert: "Please login first!"
  end 
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
   def index
    @doctors = current_user.doctors
    @appointments = current_user.appointments
  end

  def show
    @appointment = current_user.appointments
  end

  def new
    @appointment = Appointment.new
    @doctors = current_user.doctors
  end

  def edit
    @doctors = current_user.doctors
    @appointment = Appointment.find(params[:id])
  end

  def create
   @appointment = Appointment.new(appointment_params)
   @appointment.user_id = current_user.id
   if @appointment.save
      redirect_to :profile, notice: "Appointment was added!"
    else
       flash.now[:alert] = "Error saving appointment"
      render :new
    end 
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update_attributes(appointment_params)
      redirect_to :profile
    else
      render :edit
    end 
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to appointment_path
  end

  def history 
    @doctors = current_user.doctors
    @appointments = current_user.appointments
  end 

  private
  def appointment_params
    params.require(:appointment).permit(:date, :time, :note, :doctor_id, :id)
  end 
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = current_user.doctors
  end

  def show
    # @doctor = current_user.doctors
    @doctor = Doctor.find(params[:id])
    @appointments = current_user.appointments
  end

  def new
    @doctor = Doctor.new
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def create
   @doctor = Doctor.new(doctor_params)
   @doctor.user_id = current_user.id
   if @doctor.save
      redirect_to :profile, notice: "Doctor was added!"
    else
       flash.now[:alert] = "Error saving doctor"
      render :new
    end 
  end

  def update
    @doctor = Doctor.find(params[:id])
    if @doctor.update_attributes(doctor_params)
      redirect_to :profile
    else
      render :edit
    end 
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to doctors_path
  end

  private
  def doctor_params
    params.require(:doctor).permit(:name, :title, :phone, :alt_phone, :address, :id)
  end 
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
 def index
    @medications = current_user.medications
  end

  def show
    @medication = current_user.medications
  end

  def new
    @medication = Medication.new
  end

  def edit
    @medication = Medication.find(params[:id])
  end

  def create
   @medication = Medication.new(medication_params)
   @medication.user_id = current_user.id
   if @medication.save
      redirect_to :profile, notice: "Medication was added!"
    else
       flash.now[:alert] = "Error saving medication"
      render :new
    end 
  end

  def update
    @medication = Medication.find(params[:id])
    if @medication.update_attributes(medication_params)
      redirect_to :profile
    else
      render :edit
    end 
  end

  def destroy
    @medication = Medication.find(params[:id])
    @medication.destroy
    redirect_to medications_path
  end

  private
  def medication_params
    params.require(:medication).permit(:name, :amount, :started_at, :ended_at, :id)
  end 
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:profile, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:login, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create]
 
  def index
    @users = User.all
  end

  def show
     @medications = current_user.medications
     @doctors = current_user.doctors
     # @doctor = @doctors.find(params[:id])
     @appointments = current_user.appointments

     @recent = Appointment.most_recent.map {|appt| appt.date.strftime('%b %d, %Y')}
     @recent_doctor = Appointment.most_recent.map {|appt| appt.doctor.name}

     @next = Appointment.next_appt.map {|appt| appt.date.strftime('%b %d, %Y')}
     @next_doctor = Appointment.next_appt.map {|appt| appt.doctor.name}
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        auto_login(@user)
        format.html { redirect_to :profile, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      # @user = User.find(params[:id])
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation, :email, :crypted_password, :salt)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_field :time %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br>
    <%= f.select :doctor_id, @doctors.map{ |d| [d.name, d.id] } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Update Appointment</h1>

<%= render 'form'%>

app/views/appointments/history.html.erb
<h1>Appointment History</h1>
<p>can print to pdf?</p>

<ul>
    <% @appointments.each do |appointment| %>
      <p>
      Appointment on <%= appointment.date.strftime('%b %d, %Y') %>
      with <%= appointment.doctor.name %></br>
        <% if appointment.note != "" %>
           Notes: <%= appointment.note %> </br>
        <% end %>
    <% end %>
</ul>

app/views/appointments/index.html.erb
<h1>All Appointments</h1>

<%= link_to 'Add an Appointment', new_appointment_path %>
<ul>
    <% @appointments.each do |appointment| %>
      <p>
      Appointment on <%= appointment.date.strftime('%b %d, %Y') %>
      at <%= appointment.time.strftime('%I:%M:%S %p') %>
      with <%= appointment.doctor.name %> at <%= appointment.doctor.address %></br>
        <% if appointment.note != "" %>
           Notes: <%= appointment.note %> </br>
        <% end %>
      <%= link_to 'Update', edit_appointment_path(appointment.id) %> |
      <%= link_to 'Delete', appointment, method: :delete, data: {confirm: "Are you sure you want to delete this appointment?"}  %>
      </p>
    <% end %>
</ul>

app/views/appointments/new.html.erb
<h1>Add a new Appointment</h1>

<%= render 'form'%>

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
 <div class="field">
    <%= f.label :alt_phone %><br>
    <%= f.text_field :alt_phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Update Information for <%= @doctor.name%></h1>

<%= render 'form'%>

app/views/doctors/new.html.erb
<h1>Add a new Doctor</h1>

<%= render 'form'%>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>
<h3>Info:</h3>
<%= @doctor.phone %></br>
<%= @doctor.address %></br>

<h3>Appointments with <%= @doctor.name %></h3>
<ul>
  <% @appointments.each do |appointment| %>
    <% if appointment.doctor.name ==  @doctor.name %>
      <p>
        Appointment on <%= appointment.date.strftime('%b %d, %Y') %>
        at <%= appointment.time.strftime('%I:%M:%S %p') %></br>
       <!--  with <%= appointment.doctor.name %></br> -->
        <% if appointment.note != "" %>
          Notes: <%= appointment.note %> </br>
          <% end %>
          <%= link_to 'Update', edit_appointment_path(appointment.id) %>
      </p>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthTrackr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>HealthTrackr</h1>
  <div id="nav">
    <% if current_user %>
      <%= link_to 'Your Profile', :profile %> |
      <%= link_to 'Your Medications', medications_path %> |
      <%= link_to 'All Appointments', appointments_path %> |
      <%= link_to "Logout", :logout, method: :post %>

    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
  </div>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>

<%= yield %>

</body>
</html>

app/views/medications/_form.html.erb
<%= form_for(@medication) do |f| %>
  <% if @medication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medication.errors.count, "error") %> prohibited this medication from being saved:</h2>

      <ul>
      <% @medication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :started_at %><br>
    <%= f.date_field :started_at %>
  </div>
  <div class="field">
   <%= f.label :ended_at%><br />
   <%= f.date_field :ended_at %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medications/edit.html.erb
<h1>Update <%= @medication.name %></h1>

<%= render 'form'%>

app/views/medications/index.html.erb
<h1>Your medications</h1>

<%= link_to 'Add a medication', new_medication_path %>
<ul>
    <% @medications.each do |medication| %>
  <p>
  Name: <%= medication.name %></br>
  Amount: <%= medication.amount %></br>
  Started On: <%= medication.started_at.strftime('%b %d, %Y') %></br>
  <% if medication.ended_at != nil %>
    Ended On: <%= medication.ended_at.strftime('%b %d, %Y') %></br>
    <% end %>
    <%= link_to 'Update', edit_medication_path(medication.id) %> |
    <%= link_to 'Delete', medication, method: :delete, data: {confirm: "Are you sure you want to delete this medication?"}  %>
  </p>
    <% end %>
  </ul>

app/views/medications/new.html.erb
<h1>Add a new medication</h1>

<%= render 'form'%>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
</div>
<div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Hi <%= current_user.first_name %></h1>

<h3>Summary</h3>
<p>Your last appointment was on <%= @recent[0] %> with <%= @recent_doctor[0] %>.
</br>You're next appointment is <%= @next[0] %> with <%= @next_doctor[0]%>. </p>

<h3>Medications</h3>
<p>Your Current Medications</p>
<ul>
  <% @medications.each do |medication| %>
    <% if (medication.ended_at == nil) || (medication.ended_at > Time.now) %>
      <p>
        Name: <%= medication.name %></br>
        Dosage: <%= medication.amount %></br>
        Started On: <%= medication.started_at.strftime('%b %d, %Y') %>
      </p>
    <% end %>
  <% end %>
</ul>

<h3>Appointments and Visits</h3>
<ul>
  <% @appointments.each do |appointment| %>
    <% if (appointment.date < Date.today + 3.months) && (appointment.date > Date.today) %>
      <p>
        Appointment on <%= appointment.date.strftime('%b %d, %Y') %>
        at <%= appointment.time.strftime('%I:%M:%S %p') %>
        with <%= appointment.doctor.name %></br>
      </p>
    <% end %>
  <% end %>
</ul>

<h3>Doctors and Hospitals</h3>
<%= link_to 'Add a Doctor or a Hospital', new_doctor_path %> 
<ul>
  <% @doctors.each do |doctor| %>
    <p>
       <%= link_to doctor.name, doctor_path(doctor.id) %> your <%= doctor.title%></br>
      Phone: <%= doctor.phone%></br>
        <% if doctor.alt_phone != "" %>
          Alternate Phone Number: <%= doctor.alt_phone %></br>
        <% end %>
      Address: <%= doctor.address %></br>
      <%= link_to 'Update', edit_doctor_path(doctor.id) %> |
      <%= link_to 'Remove', doctor, method: :delete, data: {confirm: "Are you sure you want to delete this doctor?"}  %>
    </p>
  <% end %>
</ul>

<!-- <h2>Second iteration</h2>
<p>Would like to track symptoms</p>
<p>This info should be able to be exported to a formatted chart, or pdf.</p> -->